name: Build ModMaster
description: Builds minecraft mod with ModMaster plugin

inputs:
  java-version:
    description: "Java version to use"
    required: false
    default: "25"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v7

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v6
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Build
      run: ./gradlew check build
      shell: bash

    - name: Set mod version
      run: |
        grep ^modid= gradle.properties >> $GITHUB_ENV
        grep ^mod_version= gradle.properties >> $GITHUB_ENV
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        path: "build/*.zip"
        archive: false
